// Code generated by MockGen. DO NOT EDIT.
// Source: api/services/memory_verse_service.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	models "discipleship_journal_api/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMemoryVerseService is a mock of MemoryVerseService interface.
type MockMemoryVerseService struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryVerseServiceMockRecorder
}

// MockMemoryVerseServiceMockRecorder is the mock recorder for MockMemoryVerseService.
type MockMemoryVerseServiceMockRecorder struct {
	mock *MockMemoryVerseService
}

// NewMockMemoryVerseService creates a new mock instance.
func NewMockMemoryVerseService(ctrl *gomock.Controller) *MockMemoryVerseService {
	mock := &MockMemoryVerseService{ctrl: ctrl}
	mock.recorder = &MockMemoryVerseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryVerseService) EXPECT() *MockMemoryVerseServiceMockRecorder {
	return m.recorder
}

// ClonePack mocks base method.
func (m *MockMemoryVerseService) ClonePack(ctx context.Context, packID, userID uuid.UUID, newTitle string) (*models.VersePack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClonePack", ctx, packID, userID, newTitle)
	ret0, _ := ret[0].(*models.VersePack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClonePack indicates an expected call of ClonePack.
func (mr *MockMemoryVerseServiceMockRecorder) ClonePack(ctx, packID, userID, newTitle interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClonePack", reflect.TypeOf((*MockMemoryVerseService)(nil).ClonePack), ctx, packID, userID, newTitle)
}

// CreatePack mocks base method.
func (m *MockMemoryVerseService) CreatePack(ctx context.Context, pack *models.VersePack) (*models.VersePack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePack", ctx, pack)
	ret0, _ := ret[0].(*models.VersePack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePack indicates an expected call of CreatePack.
func (mr *MockMemoryVerseServiceMockRecorder) CreatePack(ctx, pack interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePack", reflect.TypeOf((*MockMemoryVerseService)(nil).CreatePack), ctx, pack)
}

// CreateVerse mocks base method.
func (m *MockMemoryVerseService) CreateVerse(ctx context.Context, verse *models.MemoryVerse) (*models.MemoryVerse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerse", ctx, verse)
	ret0, _ := ret[0].(*models.MemoryVerse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerse indicates an expected call of CreateVerse.
func (mr *MockMemoryVerseServiceMockRecorder) CreateVerse(ctx, verse interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerse", reflect.TypeOf((*MockMemoryVerseService)(nil).CreateVerse), ctx, verse)
}

// DeletePack mocks base method.
func (m *MockMemoryVerseService) DeletePack(ctx context.Context, packID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePack", ctx, packID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePack indicates an expected call of DeletePack.
func (mr *MockMemoryVerseServiceMockRecorder) DeletePack(ctx, packID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePack", reflect.TypeOf((*MockMemoryVerseService)(nil).DeletePack), ctx, packID, userID)
}

// GetPack mocks base method.
func (m *MockMemoryVerseService) GetPack(ctx context.Context, packID, userID uuid.UUID) (*models.VersePack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPack", ctx, packID, userID)
	ret0, _ := ret[0].(*models.VersePack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPack indicates an expected call of GetPack.
func (mr *MockMemoryVerseServiceMockRecorder) GetPack(ctx, packID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPack", reflect.TypeOf((*MockMemoryVerseService)(nil).GetPack), ctx, packID, userID)
}

// GetPacks mocks base method.
func (m *MockMemoryVerseService) GetPacks(ctx context.Context, userID uuid.UUID, typeFilter string) ([]*models.VersePack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPacks", ctx, userID, typeFilter)
	ret0, _ := ret[0].([]*models.VersePack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPacks indicates an expected call of GetPacks.
func (mr *MockMemoryVerseServiceMockRecorder) GetPacks(ctx, userID, typeFilter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPacks", reflect.TypeOf((*MockMemoryVerseService)(nil).GetPacks), ctx, userID, typeFilter)
}

// GetVerses mocks base method.
func (m *MockMemoryVerseService) GetVerses(ctx context.Context, packID uuid.UUID) ([]*models.MemoryVerse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerses", ctx, packID)
	ret0, _ := ret[0].([]*models.MemoryVerse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerses indicates an expected call of GetVerses.
func (mr *MockMemoryVerseServiceMockRecorder) GetVerses(ctx, packID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerses", reflect.TypeOf((*MockMemoryVerseService)(nil).GetVerses), ctx, packID)
}
